language: perl
perl:
  - 5.16

install:
  - cpanm --quiet --notest IO::Prompt::Tiny
  - cpanm --quiet --notest Devel::Cover::Report::Coveralls
  - cpanm --quiet --notest --installdeps .

after_success:
  - cover -report coveralls
